only install VirtualBox guest additions if they're there
In libvirt boxes, they will never be there, and even in VirtualBox boxes
they might not be since we can probably get away without them.

diff --git a/kiwi/cloud-admin/source/root/studio/suse-studio-custom b/kiwi/cloud-admin/source/root/studio/suse-studio-custom
--- a/kiwi/cloud-admin/source/root/studio/suse-studio-custom
+++ b/kiwi/cloud-admin/source/root/studio/suse-studio-custom
@@ -20,16 +20,17 @@ then
     # Reduce grub prompt time-out
     sed -i 's/^timeout [0-9]\+/timeout 3/' /boot/grub/menu.lst
 
-    echo "Installing VirtualBox guest additions ..."
-    # Unfortunately the return code can be non-zero even when
-    # it worked.
-    sh /tmp/VBoxLinuxAdditions.run
-    if lsmod | grep vbox; then
-        echo "VirtualBox guest additions installed!"
-        echo "Removing kernel source and headers ..."
-        rpm -e kernel-default-devel kernel-source
-    else
-        cat <<EOF >&2
+    if [ -f /tmp/VBoxLinuxAdditions.run ]; then
+        echo "Installing VirtualBox guest additions ..."
+        sh /tmp/VBoxLinuxAdditions.run
+        # Unfortunately the return code can be non-zero even when
+        # it worked.
+        if lsmod | grep vbox; then
+            echo "VirtualBox guest additions installed!"
+            echo "Removing kernel source and headers ..."
+            rpm -e kernel-default-devel kernel-source
+        else
+            cat <<EOF >&2
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 WARNING: VirtualBox guest additions failed to install.
@@ -37,5 +38,8 @@ Probably worth checking /var/log/vboxadd-install.log.
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 EOF
+        fi
+    else
+        echo "/tmp/VBoxLinuxAdditions.run not present; won't install VirtualBox guest additions."
     fi
 fi
