add 192.168.124.10 entry to /etc/hosts

diff --git a/kiwi/source/root/studio/build-custom b/kiwi/source/root/studio/build-custom
--- a/kiwi/source/root/studio/build-custom
+++ b/kiwi/source/root/studio/build-custom
@@ -19,8 +19,25 @@ if test -f /.kconfig; then
     . /.kconfig
 fi
 
+die () {
+    echo >&2 "$*"
+    exit 1
+}
+
 echo "Removing EULA on first boot ..."
 rm /etc/YaST2/licenses/license.txt
+
+if ! long_hostname="`cat /etc/HOSTNAME`"; then
+    die "Failed to determine hostname"
+fi
+short_hostname="${long_hostname%%.*}"
+if [ "$short_hostname" = "$long_hostname" ]; then
+    die "Failed to determine FQDN for hostname ($short_hostname)"
+fi
+ADMIN_IP=192.168.124.10
+if ! grep -q "^$ADMIN_IP " /etc/hosts; then
+    echo "$ADMIN_IP   $long_hostname $short_hostname" >> /etc/hosts
+fi
 
 echo "Enabling auto-start of ntp and ssh services on boot ..."
 chkconfig ntp on
